# Generated by Django 4.1.3 on 2023-03-13 22:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_usermodel_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(7, message='Your password is too short! Minimum of 8 length is required')]),
        ),
    ]
