# Generated by Django 4.1.3 on 2023-03-14 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_usermodel_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='otp',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
