# Generated by Django 4.1.3 on 2023-03-16 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_usermodel_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='username',
        ),
    ]
