# Generated by Django 4.1.3 on 2023-03-16 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_usermodel_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='email',
        ),
    ]
