# Generated by Django 4.1.3 on 2023-02-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citizens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('birth_date', models.DateField()),
                ('nin', models.CharField(max_length=10, unique=True)),
                ('phone_number', models.CharField(max_length=11, null=True)),
            ],
        ),
    ]
