# Generated by Django 4.1.3 on 2023-04-18 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feds', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Citizens',
            new_name='Citizen',
        ),
    ]
