# Generated by Django 4.1.3 on 2023-02-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feds', '0002_citizens_email_field_alter_citizens_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizens',
            name='email_field',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
