# Generated by Django 4.1.3 on 2023-02-28 09:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feds', '0004_alter_citizens_nin_alter_citizens_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizens',
            name='profile_pics',
            field=models.ImageField(default='blank_profile_pic.png', upload_to='profile_image'),
        ),
        migrations.AlterField(
            model_name='citizens',
            name='nin',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinLengthValidator(11, message='Your NIN should be 11 digit numbers'), django.core.validators.MaxLengthValidator(11)]),
        ),
    ]
