# Generated by Django 4.1.3 on 2023-02-28 11:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feds', '0005_citizens_profile_pics_alter_citizens_nin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizens',
            name='nin',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(11, message='Your NIN should be 11 digit numbers'), django.core.validators.MaxLengthValidator(11)]),
        ),
    ]
