# Generated by Django 4.1.3 on 2023-02-28 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feds', '0006_alter_citizens_nin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citizens',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
