# Generated by Django 4.1.3 on 2023-03-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feds', '0008_rename_email_field_citizens_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizens',
            name='phone',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
