# Generated by Django 4.1.3 on 2023-03-04 19:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nin', models.CharField(max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(11, message='Your NIN should be 11 digit numbers'), django.core.validators.MaxLengthValidator(11)])),
                ('birth_date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Accreditation',
        ),
    ]
