# Generated by Django 4.1.3 on 2023-03-06 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_2', '0002_verification_delete_accreditation'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseOfRepsCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('profile_pics', models.ImageField(default='blank_profile_pic.png', upload_to='profile_image')),
            ],
        ),
        migrations.CreateModel(
            name='PresidentialCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('profile_pics', models.ImageField(default='blank_profile_pic.png', upload_to='profile_image')),
            ],
        ),
        migrations.CreateModel(
            name='SenatorialCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('profile_pics', models.ImageField(default='blank_profile_pic.png', upload_to='profile_image')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('states', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizen_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core_2.verification')),
                ('citizen_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_2.state')),
                ('house_of_reps_vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_2.houseofrepscandidate')),
                ('president_vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_2.presidentialcandidate')),
                ('senatorial_vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_2.senatorialcandidate')),
            ],
        ),
    ]
