# Generated by Django 4.1.3 on 2023-03-06 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_2', '0003_houseofrepscandidate_presidentialcandidate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='election',
            old_name='citizen_details',
            new_name='citizen_nin',
        ),
    ]
