# Generated by Django 4.1.3 on 2023-03-07 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_2', '0006_alter_election_citizen_nin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presidentialcandidate',
            options={'ordering': ['first_name']},
        ),
        migrations.RenameField(
            model_name='election',
            old_name='president_vote',
            new_name='candidate',
        ),
        migrations.RemoveField(
            model_name='election',
            name='house_of_reps_vote',
        ),
        migrations.RemoveField(
            model_name='election',
            name='senatorial_vote',
        ),
    ]
