# Generated by Django 4.1.3 on 2023-03-07 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_2', '0008_alter_election_citizen_nin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='election',
            old_name='citizen_nin',
            new_name='voters_nin',
        ),
        migrations.RenameField(
            model_name='election',
            old_name='citizen_state',
            new_name='voters_state',
        ),
    ]
