# Generated by Django 4.1.3 on 2023-03-15 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_2', '0009_rename_citizen_nin_election_voters_nin_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HouseOfRepsCandidate',
        ),
        migrations.DeleteModel(
            name='SenatorialCandidate',
        ),
    ]
