# Generated by Django 4.1.3 on 2023-04-18 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0002_rename_candidatevotes_candidatevote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidatevote',
            name='vote_count',
        ),
        migrations.AddField(
            model_name='candidatevote',
            name='election',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polling.election'),
            preserve_default=False,
        ),
    ]
