# Generated by Django 4.1.3 on 2023-04-22 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0003_remove_candidatevote_vote_count_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CandidateVote',
        ),
    ]
